language: java
branches:
  only:
  - master
install:
    - ./gradlew assemble

before_script:
    - chmod +x gradlew

script:
    - ./gradlew check
    - ./gradlew jacocoTestReport

after_success:
    - bash <(curl -s https://codecov.io/bash)